### ISSUE TITLE
HANNIBAL_DEBUG is not defined

### ISSUE THREAD

**Issue by kamirr** [agentx-cgn/Hannibal#3]
Hi, I installed mod in the proper directory and turned it on in settings, sadly I got some errors, here's log:

`--------: HANNIBAL.MODUL: Tue Apr 19 2016 19:54:20 GMT+0200 (CEST) --- ### --- ### --- ### ---
ERROR: JavaScript error: simulation/ai/hannibal/hannibal.js line 12754
ReferenceError: HANNIBAL_DEBUG is not defined
  H.Launcher@simulation/ai/hannibal/hannibal.js:12754:7
  InitGame@simulation/helpers/InitGame.js:56:4
ERROR: Failed to create AI player: simulation/ai/hannibal/data.json: error calling constructor 'Launcher'
`
Tested on build 17.04.2016.

**Comment by arcticio** [comment]
Use the launcher to start 0 A.D., it creates missing files on the fly.

**Comment by agentx-cgn** [comment]
Use the launcher to start  0 A.D., it creates the missing files.
