### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by faerietree** [agentx-cgn/Hannibal#6]
The design is difficult to maintain.
Again - large parts belong into the engine instead of repeating logic in the HannibalAI bot.

Do you know how to code CPP by now?

**Comment by StanleySweet** [comment]
That sounds like a good idea. You should check whether it makes sense at all to do those changes to the engine, and submit a patch upstream afterwards, when you have fixed it.

**Comment by agentx-cgn** [comment]
Not a good place to discuss speculations.... Closed
